#ci.yaml file 

name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install
        working-directory: ./codebase/rdicidr-0.1.0

      - name: Run linter
        run: npm run lint
        working-directory: ./codebase/rdicidr-0.1.0

      - name: Run formatter
        run: npm run prettier
        working-directory: ./codebase/rdicidr-0.1.0

      - name: Run tests
        env:
          CI: true
        run: npm run test
        working-directory: ./codebase/rdicidr-0.1.0

      - name: Build project
        run: npm run build
        working-directory: ./codebase/rdicidr-0.1.0